In [2]:
import pandas as pd

df = pd.read_parquet("../data/raw_data_full.parquet")
df["datetime"] = pd.to_datetime(df["datetime"])
print(df.head())
print(df.dtypes)

             datetime  season  yr  mnth  hr  holiday  weekday  workingday  \
0 2011-01-01 00:00:00       1   0     1   0        0        6           0
1 2011-01-01 01:00:00       1   0     1   1        0        6           0
2 2011-01-01 02:00:00       1   0     1   2        0        6           0
3 2011-01-01 03:00:00       1   0     1   3        0        6           0
4 2011-01-01 04:00:00       1   0     1   4        0        6           0

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt
0           1  0.24  0.2879  0.81        0.0       3          13   16
1           1  0.22  0.2727  0.80        0.0       8          32   40
2           1  0.22  0.2727  0.80        0.0       5          27   32
3           1  0.24  0.2879  0.75        0.0       3          10   13
4           1  0.24  0.2879  0.75        0.0       0           1    1
datetime      datetime64[us]
season                 int64
yr                     int64
mnth                   int64
hr                     int64
holiday                int64
weekday                int64
workingday             int64
weathersit             int64
temp                 float64
atemp                float64
hum                  float64
windspeed            float64
casual                 int64
registered             int64
cnt                    int64
dtype: object

In [3]:
df["lag_1h"] = df["cnt"].shift(1)
df["lag_24h"] = df["cnt"].shift(24)
df["lag_168h"] = df["cnt"].shift(168)
df.head(10)
df = df.dropna()
df.head(10)

,datetime,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,lag_1h,lag_24h,lag_168h
168,2011-01-08 07:00:00,1,0,1,7,0,6,0,2,0.16,0.1818,0.74,0.1045,1,8,9,2.0,84.0,16.0
169,2011-01-08 08:00:00,1,0,1,8,0,6,0,3,0.16,0.1818,0.93,0.1045,0,15,15,9.0,210.0,40.0
170,2011-01-08 09:00:00,1,0,1,9,0,6,0,3,0.16,0.1818,0.93,0.1045,0,20,20,15.0,134.0,32.0
171,2011-01-08 10:00:00,1,0,1,10,0,6,0,2,0.18,0.1970,0.80,0.1642,5,56,61,20.0,63.0,13.0
172,2011-01-08 11:00:00,1,0,1,11,0,6,0,2,0.20,0.1818,0.69,0.3881,2,60,62,61.0,67.0,1.0
173,2011-01-08 12:00:00,1,0,1,12,0,6,0,2,0.20,0.1818,0.59,0.3582,8,90,98,62.0,59.0,1.0
174,2011-01-08 13:00:00,1,0,1,13,0,6,0,1,0.20,0.1818,0.44,0.3284,7,95,102,98.0,73.0,2.0
175,2011-01-08 14:00:00,1,0,1,14,0,6,0,1,0.20,0.1667,0.32,0.4925,12,83,95,102.0,50.0,3.0
176,2011-01-08 15:00:00,1,0,1,15,0,6,0,1,0.20,0.1667,0.32,0.4478,5,69,74,95.0,72.0,8.0
177,2011-01-08 16:00:00,1,0,1,16,0,6,0,1,0.18,0.1364,0.29,0.4478,8,68,76,74.0,87.0,14.0

In [8]:
df["rolling_mean_3h"] = df["cnt"].rolling(window=3).mean()
df["rolling_mean_24h"] = df["cnt"].rolling(window=24).mean()
df = df.dropna()
print(df.shape)
df.head(10)

(17142, 21)

,datetime,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,...,hum,windspeed,casual,registered,cnt,lag_1h,lag_24h,lag_168h,rolling_mean_3h,rolling_mean_24h
237,2011-01-11 06:00:00,1,0,1,6,0,2,1,2,0.16,...,0.55,0.1343,0,27,27,6.0,3.0,5.0,12.000000,56.625000
238,2011-01-11 07:00:00,1,0,1,7,0,2,1,2,0.16,...,0.55,0.0000,2,97,99,27.0,3.0,2.0,44.000000,60.625000
239,2011-01-11 08:00:00,1,0,1,8,0,2,1,2,0.18,...,0.51,0.0896,3,214,217,99.0,31.0,1.0,114.333333,68.375000
240,2011-01-11 09:00:00,1,0,1,9,0,2,1,2,0.18,...,0.51,0.1642,3,127,130,217.0,77.0,2.0,148.666667,70.583333
241,2011-01-11 10:00:00,1,0,1,10,0,2,1,2,0.20,...,0.51,0.1642,3,51,54,130.0,188.0,4.0,133.666667,65.000000
242,2011-01-11 11:00:00,1,0,1,11,0,2,1,2,0.20,...,0.47,0.1343,4,31,35,54.0,94.0,36.0,73.000000,62.541667
243,2011-01-11 12:00:00,1,0,1,12,0,2,1,2,0.20,...,0.51,0.1045,2,55,57,35.0,31.0,94.0,48.666667,63.625000
244,2011-01-11 13:00:00,1,0,1,13,0,2,1,2,0.20,...,0.59,0.0896,6,46,52,57.0,30.0,179.0,48.000000,64.541667
245,2011-01-11 14:00:00,1,0,1,14,0,2,1,2,0.20,...,0.59,0.0896,3,60,63,52.0,52.0,100.0,57.333333,65.000000
246,2011-01-11 15:00:00,1,0,1,15,0,2,1,2,0.16,...,0.80,0.0896,2,45,47,63.0,54.0,42.0,54.000000,64.708333

In [9]:
df.to_parquet("../data/processed_data.parquet")